#!/usr/bin/env python

from __future__ import print_function

import pprint

import bugzilla

def bz_in_rn (bz_api, version):
  # This function takes the bzapi, the version in format '11.6.x' and returns 
  # a list of all BZ included in the PD release note on ASKF5.
  # eg: 11.6.x include TMOS v11.6.1, TMOS v11.6.0, TMOS v11.6.1 HF-TMOS, TMOS v11.6.0 HF-APM, ...
  # The conditons are:
  #   -Version = $version
  #   -Release Note = Yes / or Parent Bug has Release Note = Yes
  #   -Type = Defect/Crash/Performance/Regression/Usability
  
  # Login to bugzilla
  bz_user = 'xxxxx@xx.com'
  bz_pass = 'xxxxxx'
  bz_api.login(bz_user, bz_pass)
  
  # Need a better way to get the versions; maybe a regular expression... Following list is for 11.6.1 as of 08/17/16
  version_list = ['TMOS v11.6.0 ', 'TMOS v11.6.0 HF-APM', 'TMOS v11.6.0 HF-ASM', 'TMOS v11.6.0 HF-PLATFORM', 'TMOS v11.6.0 HF-TMOS',
    'TMOS v11.6.0 HF1', 'TMOS v11.6.0 HF2', 'TMOS v11.6.0 HF3', 'TMOS v11.6.0 HF4', 'TMOS v11.6.0 HF5', 'TMOS v11.6.0 HF6', 'TMOS v11.6.0 HF7',
    'TMOS v11.6.0 HF8', 'TMOS v11.6.1 ', 'TMOS v11.6.1 HF-APM', 'TMOS v11.6.1 HF-ASM', 'TMOS v11.6.1 HF-PLATFORM', 'TMOS v11.6.1 HF-TMOS',
    'TMOS v11.6.1 HF1']
  # Type of bz expected in the RN; with the intentional omission of 'Vuneraliblity'
  type_list = ['Defect', 'Crash', 'Performance', 'Regression', 'Usability']
  
  # Query for all bz with version_list and type_list; return only include_fields
  query_bz = bz_api.build_query(
    classification='TMOS',
    product='BIG-IP',
    cf_type=type_list,
    version=version_list,
    include_fields=["id", "bug_status", "resolution", "cf_type", "bug_severity", "summary"])

  # Performing the Query 
  #t1 = time.time()
  bz_in_rn_list = bz_api.query(query_bz)
  return bz_in_rn_list
  #t2 = time.time()
  #print("Found %d bugs with our query" % len(bugs))
  #print("Query processing time: %s" % (t2 - t1))
  
